<?php

namespace ContainerY4fPpHk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LqgSBY7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LqgSBY7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LqgSBY7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'orderRepository' => ['privates', 'App\\Repository\\OrderRepository', 'getOrderRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'orderRepository' => 'App\\Repository\\OrderRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
