<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY4fPpHk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY4fPpHk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY4fPpHk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY4fPpHk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY4fPpHk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y4fPpHk',
    'container.build_id' => '9d3f7ebd',
    'container.build_time' => 1641597467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY4fPpHk');
