<?php

namespace Container4pf3nnT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BmxGMTWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bmxGMTW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bmxGMTW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContactController::contact' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\FooterController::category' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\FooterController::products' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\OrderController::index' => ['privates', '.service_locator.LqgSBY7', 'get_ServiceLocator_LqgSBY7Service', true],
            'App\\Controller\\OrderController::order' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ProductController::addProduct' => ['privates', '.service_locator.0D6zgt7', 'get_ServiceLocator_0D6zgt7Service', true],
            'App\\Controller\\ProductController::createProduct' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ProductController::showAll' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ProductController::showById' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::showCategoryByName' => ['privates', '.service_locator.n2Y3z8T', 'get_ServiceLocator_N2Y3z8TService', true],
            'App\\Controller\\RegisterController::reg' => ['privates', '.service_locator.meNJ0Yn', 'get_ServiceLocator_MeNJ0YnService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.SxWgT3I', 'get_ServiceLocator_SxWgT3IService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ContactController:contact' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\FooterController:category' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\FooterController:products' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\OrderController:index' => ['privates', '.service_locator.LqgSBY7', 'get_ServiceLocator_LqgSBY7Service', true],
            'App\\Controller\\OrderController:order' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ProductController:addProduct' => ['privates', '.service_locator.0D6zgt7', 'get_ServiceLocator_0D6zgt7Service', true],
            'App\\Controller\\ProductController:createProduct' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ProductController:showAll' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\ProductController:showById' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:showCategoryByName' => ['privates', '.service_locator.n2Y3z8T', 'get_ServiceLocator_N2Y3z8TService', true],
            'App\\Controller\\RegisterController:reg' => ['privates', '.service_locator.meNJ0Yn', 'get_ServiceLocator_MeNJ0YnService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.SxWgT3I', 'get_ServiceLocator_SxWgT3IService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ContactController::contact' => '?',
            'App\\Controller\\FooterController::category' => '?',
            'App\\Controller\\FooterController::products' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\OrderController::index' => '?',
            'App\\Controller\\OrderController::order' => '?',
            'App\\Controller\\ProductController::addProduct' => '?',
            'App\\Controller\\ProductController::createProduct' => '?',
            'App\\Controller\\ProductController::showAll' => '?',
            'App\\Controller\\ProductController::showById' => '?',
            'App\\Controller\\ProductController::showCategoryByName' => '?',
            'App\\Controller\\RegisterController::reg' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ContactController:contact' => '?',
            'App\\Controller\\FooterController:category' => '?',
            'App\\Controller\\FooterController:products' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\OrderController:index' => '?',
            'App\\Controller\\OrderController:order' => '?',
            'App\\Controller\\ProductController:addProduct' => '?',
            'App\\Controller\\ProductController:createProduct' => '?',
            'App\\Controller\\ProductController:showAll' => '?',
            'App\\Controller\\ProductController:showById' => '?',
            'App\\Controller\\ProductController:showCategoryByName' => '?',
            'App\\Controller\\RegisterController:reg' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
